### ISSUE TITLE
base design todo

### ISSUE THREAD

**Issue by kristiwalker** [mcclatchy/special-project-template#1]
Design/Build
- [x]  Datawrapper embeds
- [ ]  Video embeds
- [ ]  Social buttons embeds
- [ ]  Fact boxes
- [x]  Generic navbar
- [ ]  Generic bottom nav
- [x]  Related articles section
- [x]  Pull quotes
- [x]  PHP templating
- [ ] add transitions
- [x] refactor for clarity
- [x] simplify sass
- [x] rename classes/ids with bd-
- [ ] check all resets
- [x] add CSS table of contents
- [ ] change header name to prevent confusion with headers and header sections

Documentation
- [ ]  Paste embeds with any notes
- [ ]  Document css classes (colors, borders)
