### ISSUE TITLE
General To-Do's

### ISSUE THREAD

**Issue by kristiwalker** [mcclatchy/special-project-template#2]
- [ ] Remove padding to photo captions

- [ ] Remove margin/padding when scrolling left/right (caused from Bootstrap container/row)

- [ ] Add <a> to byline

- [ ] Remove view sources button at top of story

- [ ] Remove padding on share icons

- [ ] Update share icons JS from VFX project updates

- [ ] Remove pull quotes

- [ ] Update figure blocks

- [ ] Add more margin between photos/graphics and story text

- [ ] Make subhead larger with more margin

- [ ] Redesign comments/More stories header

- [ ] Change suggested stories to "More stories"

- [ ] Add script to bump ads before comments

- [ ] Redesign intro style/dropcap

- [ ] Add credits redesign from VFX

- [ ] Add sources redesign from VFX

- [ ] Make <p> wider on larger screens

- [ ] Make template for arthead over photo

- [ ] Add Herald Sun to newsrooms JSON + color stylesheet

- [ ] Add new McClatchy DC Bureau to color stylesheet

- [ ] Add commented out "last updated" div at top of intro

- [ ] Standardize <a> tag style for links

- [ ] Redesign more stories section with https://apps.bostonglobe.com/graphics/2016/04/arresting-words/ as inspiration

- [ ] Adjust rem vs em depending on if the item scaled based on font-size
